---
name: CI
on:
  pull_request:
  push:
    branches:
      - master

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      # - uses: editorconfig-checker/editorconfig-checker-action@v1

      - uses: actions/setup-go@v4
        with:
          go-version: "1.24"

      - uses: bazel-contrib/setup-bazel@0.14.0
        with:
          # Avoid downloading Bazel every time.
          bazelisk-cache: true
          # Store build cache per workflow.
          disk-cache: ${{ github.workflow }}
          # Share repository cache between workflows.
          repository-cache: true

      - run: scripts/update-deps.sh
      - run: scripts/build.sh serve-http
      - run: go vet ./...

      - name: Check formatting
        run: |
          files=$(find . -name '*.go' ! -name '*.pb.go')
          if [ -n "$files" ]; then
            unformatted=$(gofmt -l $files)
            if [ -n "$unformatted" ]; then
              echo "❌ gofmt failed on the following files:"
              echo "$unformatted"
              exit 1
            fi
          fi
